package com.oralscan.app.ui.theme

import androidx.compose.ui.graphics.Color

// Clinical teal palette (Material 3 tonal values).
val TealLightPrimary = Color(0xFF006A6A)
val TealLightPrimaryContainer = Color(0xFF9CF1F0)
val TealLightOnPrimaryContainer = Color(0xFF002020)
val TealLightSecondary = Color(0xFF4A6363)
val TealLightSecondaryContainer = Color(0xFFCCE8E7)
val TealLightOnSecondaryContainer = Color(0xFF051F1F)
val TealLightTertiary = Color(0xFF4B607C)
val TealLightTertiaryContainer = Color(0xFFD3E4FF)
val TealLightOnTertiaryContainer = Color(0xFF041C35)
val TealLightBackground = Color(0xFFF4FBFA)
val TealLightOnBackground = Color(0xFF161D1D)
val TealLightSurfaceVariant = Color(0xFFDAE5E4)
val TealLightOnSurfaceVariant = Color(0xFF3F4948)
val TealLightOutline = Color(0xFF6F7979)
val TealLightOutlineVariant = Color(0xFFBEC9C8)
val TealLightContainerLowest = Color(0xFFFFFFFF)
val TealLightContainerLow = Color(0xFFEEF5F4)
val TealLightContainer = Color(0xFFE9EFEE)
val TealLightContainerHigh = Color(0xFFE3E9E9)
val TealLightContainerHighest = Color(0xFFDDE4E3)

val TealDarkPrimary = Color(0xFF80D5D4)
val TealDarkOnPrimary = Color(0xFF003737)
val TealDarkPrimaryContainer = Color(0xFF004F4F)
val TealDarkOnPrimaryContainer = Color(0xFF9CF1F0)
val TealDarkSecondary = Color(0xFFB0CCCB)
val TealDarkSecondaryContainer = Color(0xFF324B4B)
val TealDarkOnSecondaryContainer = Color(0xFFCCE8E7)
val TealDarkTertiary = Color(0xFFB3C8E8)
val TealDarkTertiaryContainer = Color(0xFF334863)
val TealDarkOnTertiaryContainer = Color(0xFFD3E4FF)
val TealDarkBackground = Color(0xFF0E1515)
val TealDarkOnBackground = Color(0xFFDDE4E3)
val TealDarkSurfaceVariant = Color(0xFF3F4948)
val TealDarkOnSurfaceVariant = Color(0xFFBEC9C8)
val TealDarkOutline = Color(0xFF899392)
val TealDarkOutlineVariant = Color(0xFF3F4948)
val TealDarkContainerLowest = Color(0xFF090F0F)
val TealDarkContainerLow = Color(0xFF161D1D)
val TealDarkContainer = Color(0xFF1A2121)
val TealDarkContainerHigh = Color(0xFF252B2B)
val TealDarkContainerHighest = Color(0xFF2F3636)

// Status colors not covered by the Material scheme.
val SuccessContainerLight = Color(0xFFD7F5DD)
val OnSuccessContainerLight = Color(0xFF0B3D1A)
val SuccessContainerDark = Color(0xFF1E4D2B)
val OnSuccessContainerDark = Color(0xFFB8F0C4)
